"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RagPipeline = void 0;
const retrievalService_1 = require("./retrievalService");
const promptBuilder_1 = require("./promptBuilder");
const mongodb_1 = require("@neurovault/shared/lib/mongodb");
const Usage_1 = require("@neurovault/shared/models/Usage");
const logger_1 = require("@neurovault/shared/utils/logger");
const modelService_1 = require("./modelService");
/**
 * Orchestrates the full RAG pipeline: retrieval -> prompt construction -> generation.
 */
class RagPipeline {
    retrievalService;
    promptBuilder;
    openRouterKey;
    constructor() {
        this.retrievalService = new retrievalService_1.RetrievalService();
        this.promptBuilder = new promptBuilder_1.PromptBuilder();
        this.openRouterKey = process.env.OPENROUTER_API_KEY;
    }
    /**
     * Runs the full RAG pipeline for a given user question.
     * @param question The user's question.
     * @param userId The ID of the user (for data isolation).
     * @param strictMode Whether to rely strictly on document context.
     * @returns A promise that resolves to the generated answer.
     */
    async runQuery(question, userId, strictMode = true, model = 'openrouter/auto', similarityThreshold = 0.1) {
        const startTime = Date.now();
        try {
            logger_1.logger.info("RAG Pipeline: Query received", { userId, question, strictMode, model, similarityThreshold });
            const chunks = await this.retrievalService.retrieve(userId, question, 5, similarityThreshold);
            logger_1.logger.info("RAG Pipeline: Chunks retrieved", { count: chunks.length });
            const prompt = this.promptBuilder.buildPrompt(question, chunks, strictMode);
            if (!this.openRouterKey) {
                throw new Error("OpenRouter API key is not configured.");
            }
            const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
                method: "POST",
                headers: {
                    "Authorization": `Bearer ${this.openRouterKey}`,
                    "HTTP-Referer": "https://neurovault.local",
                    "X-Title": "NeuroVault",
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({
                    model,
                    messages: [{ role: "user", content: prompt }]
                })
            });
            if (!response.ok) {
                const errorBody = await response.text();
                logger_1.logger.error("OpenRouter API error", { status: response.status, error: errorBody });
                throw new Error(`LLM generation failed with status ${response.status}`);
            }
            const data = await response.json();
            const answer = data.choices[0]?.message?.content || "No response generated by AI.";
            // Track usage
            const tokens = data.usage?.total_tokens || 0;
            if (tokens > 0) {
                try {
                    await (0, mongodb_1.connectDB)();
                    await Usage_1.Usage.create({
                        userId,
                        tokens,
                        aiModel: model,
                        type: 'chat'
                    });
                    logger_1.logger.info("Usage tracked", { userId, tokens, model });
                }
                catch (dbErr) {
                    logger_1.logger.error("Failed to save usage data", { error: dbErr instanceof Error ? dbErr.message : 'DB error' });
                }
            }
            logger_1.logger.info("RAG Pipeline: Query completed", { durationMs: Date.now() - startTime });
            return answer;
        }
        catch (error) {
            logger_1.logger.error("RAG Pipeline Error", { error: error.message, userId });
            throw error;
        }
    }
    async runStreamingQuery(question, userId, strictMode = true, model = 'openrouter/auto', similarityThreshold = 0.1, fallbackIndex = -1 // -1 means primary model, >=0 means index in FALLBACK_MODELS
    ) {
        const FALLBACK_MODELS = [
            'openrouter/free',
            'meta-llama/llama-3.2-3b-instruct:free',
            'meta-llama/llama-3.1-8b-instruct:free',
            'google/gemma-2-9b-it:free'
        ];
        try {
            // Pre-flight check: if primary model, verify if it's still in the free registry
            if (fallbackIndex === -1 && model !== 'openrouter/free' && model !== 'openrouter/auto') {
                const isAvailable = await modelService_1.modelService.isModelAvailable(model);
                if (!isAvailable) {
                    logger_1.logger.warn(`Primary model ${model} is not in registry. Starting cascading fallback.`);
                    return this.runStreamingQuery(question, userId, strictMode, FALLBACK_MODELS[0], similarityThreshold, 0);
                }
            }
            const activeModel = fallbackIndex === -1 ? model : FALLBACK_MODELS[fallbackIndex];
            logger_1.logger.info(fallbackIndex === -1 ? "RAG Pipeline: Streaming query received" : `RAG Pipeline: Attempting Fallback Tier ${fallbackIndex + 1}`, { userId, activeModel });
            const chunks = await this.retrievalService.retrieve(userId, question, 5, similarityThreshold);
            const prompt = this.promptBuilder.buildPrompt(question, chunks, strictMode);
            if (!this.openRouterKey) {
                throw new Error("OpenRouter API key is not configured.");
            }
            const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
                method: "POST",
                headers: {
                    "Authorization": `Bearer ${this.openRouterKey}`,
                    "HTTP-Referer": "https://neurovault.local",
                    "X-Title": "NeuroVault",
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({
                    model: activeModel,
                    messages: [{ role: "user", content: prompt }],
                    stream: true
                })
            });
            if (!response.ok || !response.body) {
                let errorBody = "No error body";
                try {
                    errorBody = await response.text();
                }
                catch (e) { }
                logger_1.logger.error("OpenRouter Streaming Error", { status: response.status, error: errorBody, model: activeModel });
                // Handle 404/429/503 by CASCADING to the next fallback model
                const canRetry = (response.status === 404 || response.status === 429 || response.status === 503);
                const nextIndex = fallbackIndex + 1;
                if (canRetry && nextIndex < FALLBACK_MODELS.length) {
                    const nextModel = FALLBACK_MODELS[nextIndex];
                    logger_1.logger.warn(`Model ${activeModel} failed (${response.status}). Cascading to Tier ${nextIndex + 1}: ${nextModel}`);
                    // If rate limited, wait a bit before retrying the next tier
                    if (response.status === 429) {
                        await new Promise(resolve => setTimeout(resolve, 500 + Math.random() * 500));
                    }
                    return this.runStreamingQuery(question, userId, strictMode, model, similarityThreshold, nextIndex);
                }
                // Final failure handling if all cascades exhausted
                if (response.status === 429)
                    throw new Error("All AI providers are currently rate-limited. Try again shortly.");
                if (response.status === 503)
                    throw new Error("All stable AI models are currently overloaded. Please try again soon.");
                throw new Error(`AI Provider Error: ${response.status}`);
            }
            return response.body;
        }
        catch (error) {
            logger_1.logger.error("RAG Pipeline Critical Streaming Error", { error: error.message, userId, fallbackIndex });
            throw error;
        }
    }
}
exports.RagPipeline = RagPipeline;
